LibrarySite/urls.py
from django.contrib import admin
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView
from django.conf.urls import include, url
import library.views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', library.views.IndexPage.as_view()),
    path('add_reader/', library.views.ReaderCreate.as_view()),
    path('add_author/', library.views.AuthorCreate.as_view()),
    path('add_book/', library.views.BookCreate.as_view()),
    path('select_reader/', library.views.SelectReader.as_view()),
    path('reader/<int:libcard_id>/', library.views.ReaderIndexPage.as_view()),
    path('reader/<int:libcard_id>/get_books/', library.views.AddBooksToLibraryCard.as_view()),
    path('reader/<int:libcard_id>/return_books/', library.views.ReturnBooks.as_view()),
    path('add_books/', library.views.AddBooks.as_view()),
    path('write_off_books/', library.views.WriteOffBooks.as_view()),
    path('accounts/login/', LoginView.as_view(template_name='library/login.html', redirect_field_name='/')), # authentication_form=Form https://docs.djangoproject.com/en/2.0/topics/auth/default/#django.contrib.auth.forms.AuthenticationForm
    path('accounts/logout/', LogoutView.as_view(next_page='/accounts/login/'))
]

library/models.py
from django.db import models
from django.db.models import Sum


class Reader(models.Model):
    surname = models.CharField(max_length=100)
    name = models.CharField(max_length=100)
    patronymic = models.CharField(max_length=100)
    passportSeries = models.IntegerField()
    passportNumber = models.IntegerField()
    phoneNumber = models.CharField(max_length=12)

    class Meta:
        indexes = [models.Index(fields=["passportSeries", "passportNumber"])]


class LibraryCard(models.Model):
    yearOfIssue = models.IntegerField()
    status = models.BooleanField()
    reader = models.ForeignKey(Reader, on_delete=models.PROTECT)

    def __str__(self):
        return "%s %s %s, %i" % (self.reader.surname, self.reader.name, self.reader.patronymic, self.id)


class Author(models.Model):
    surname = models.CharField(max_length=100)
    name = models.CharField(max_length=100)
    patronymic = models.CharField(max_length=100)

    def __str__(self):
        if self.patronymic != '':
            return "%s %s %s" % (self.surname, self.name, self.patronymic)
        else:
            return "%s %s" % (self.surname, self.name)

    def short_name(self):
        if self.patronymic != '':
            return "%s %s. %s." % (self.surname, self.name[0], self.patronymic[0])
        else:
            return "%s %s." % (self.surname, self.name[0])

    class Meta:
        indexes = [models.Index(fields=["surname", "name", "patronymic"])]
        unique_together = ('surname', 'name', 'patronymic')


class Book(models.Model):
    inventoryNumber = models.CharField(max_length=100, primary_key=True)
    bookName = models.CharField(max_length=500, unique=True, db_index=True)
    authors = models.ManyToManyField(Author)
    amount = models.IntegerField()
    publishingHouse = models.CharField(max_length=100)
    yearOfPublishing = models.IntegerField()

    def __str__(self):
        authors = ""
        for author in self.authors.all():
            authors += author.short_name() + ", "
        return '"%s", Авторы: %sизд. %s, %i год, номер: %s' % (self.bookName, authors, self.publishingHouse, self.yearOfPublishing, self.inventoryNumber)
                             # ", " от авторов

    @staticmethod
    def exist_books_with_author(author):
        return len(Book.objects.filter(authors__in=[author])) != 0


class BookInLibraryCard(models.Model):
    libraryCard = models.ForeignKey(LibraryCard, on_delete=models.PROTECT)
    book = models.ForeignKey(Book, on_delete=models.PROTECT)
    amount = models.IntegerField()
    creationDate = models.DateField()
    closingDate = models.DateField(null=True)

    @staticmethod
    def books_on_hands(book):
        total = BookInLibraryCard.objects.filter(book=book, closingDate=None).aggregate(Sum('amount'))["amount__sum"]
        return total if total is not None else 0

    def __str__(self):
        return str(self.book)

library/forms.py
from django import forms
from library.models import Reader, Book, Author, LibraryCard, BookInLibraryCard
import re
import datetime

_human_name_regex = re.compile("[А-ЯЁ][а-яё]*('[А-ЯЁа-яё]+|[ -][А-ЯЁ][а-яё]*)*")

_selectpicker_widget=forms.Select(attrs={'data-live-search': 'true', "class": 'selectpicker'})

def is_valid_human_name(name):
    return _human_name_regex.fullmatch(name) is not None


class EmptyModelChoiceField(forms.MultipleChoiceField):
    def __init__(self, checker, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.checker = checker

    def valid_value(self, value):
        return self.checker(value)


class ReaderForm(forms.ModelForm):
    class Meta:
        model = Reader
        fields = ['surname', 'name', 'patronymic', 'passportSeries', 'passportNumber', 'phoneNumber']

        # ДЛЯ ЛОКАЛИЗАЦИИ
        labels = {
            'name': 'Имя',
            'surname': 'Фамилия',
            'patronymic': 'Отчество',
            'passportSeries': 'Серия',
            'passportNumber': 'Номер',
            'phoneNumber': 'Телефон'
        }
        help_texts = {
            'name': 'Введите имя читателя.',
            'surname': 'Введите фамилию читателя.',
            'patronymic': 'Введите отчество читателя.',
            'passportSeries': 'Введите серию паспорта.',
            'passportNumber': 'Введите номер паспорта.',
            'phoneNumber': 'Введите номер телефона в формате 84351234567.'
        }
        error_messages = {
            'name': {
                'max_length': 'Имя слишком длинное.',
                'empty': 'Поле не может быть пустым.',
                'incomplete': 'Поле не может быть пустым.',
            },
            'surname': {
                'max_length': 'Фамилия слишком длинная.',
                'empty': 'Поле не может быть пустым.'
            },
            'patronymic': {
                'max_length': 'Отчество слишком длинное.',
                'empty': 'Поле не может быть пустым.'
            },
            'passportSeries': {
                'max_length': 'Серия паспорта слишком длинная.',
                'empty': 'Поле не может быть пустым.'
            },
            'passportNumber': {
                'max_length': 'Номер паспорта слишком длинный.',
                'empty': 'Поле не может быть пустым.'
            },
            'phoneNumber': {
                'max_length': 'Номер телефона слишком длинный.',
                'empty': 'Поле не может быть пустым.'
            }
        }

    def clean(self):
        cleaned_data = super().clean()

        if not is_valid_human_name(cleaned_data["surname"]):
            raise forms.ValidationError("Недопустимое значение фамилии. Допускаются только русские буквы, пробел или \"-\" для составных фамилий. Первая буква должна быть заглавной.")

        if not is_valid_human_name(cleaned_data["name"]):
            raise forms.ValidationError("Недопустимое значение имени. Допускаются только русские буквы, пробел или \"-\" для составных имен. Первая буква должна быть заглавной.")

        if not is_valid_human_name(cleaned_data["patronymic"]):
            raise forms.ValidationError("Недопустимое значение отчества. Допускаются только русские буквы, пробел или \"-\" для составного отчества. Первая буква должна быть заглавной.")

        if not self.is_valid_series(cleaned_data["passportSeries"]):
            raise forms.ValidationError("Недопустимое значение серии паспорта")

        if not self.is_valid_passport_number(cleaned_data["passportNumber"]):
            raise forms.ValidationError("Недопустимое значение номера паспорта")

        if not self.is_valid_phone_number(cleaned_data["phoneNumber"]):
            raise forms.ValidationError("Недопустимое значение телефонного номера")
        return cleaned_data

    @staticmethod
    def is_valid_phone_number(number):
        return re.fullmatch("(\+7|8)[0-9]{10}", number) is not None

    @staticmethod
    def is_valid_series(series):
        return 0 <= series <= 9999

    @staticmethod
    def is_valid_passport_number(number):
        return 0 <= number <= 999999


class AuthorForm(forms.ModelForm):
    patronymic = forms.CharField(required=False, label="Отчество", help_text='Введите отчество автора')

    class Meta:
        model = Author
        fields = ['surname', 'name', 'patronymic']

        labels = {
            'surname': 'Фамилия',
            'name': 'Имя',
        }
        help_texts = {
            'surname': 'Введите фамилию автора',
            'name': 'Введите имя автора',
        }

    def clean(self):
        cleaned_data = super().clean()

        if not is_valid_human_name(cleaned_data["surname"]):
            raise forms.ValidationError("Недопустимое значение фамилии. Допускаются только русские буквы, пробел или \"-\" для составных фамилий. Первая буква должна быть заглавной.")

        if not is_valid_human_name(cleaned_data["name"]):
            raise forms.ValidationError("Недопустимое значение имени. Допускаются только русские буквы, пробел или \"-\" для составных имен. Первая буква должна быть заглавной.")

        if cleaned_data["patronymic"] != "" and not is_valid_human_name(cleaned_data["patronymic"]):
            raise forms.ValidationError("Недопустимое значение отчества. Допускаются только русские буквы, пробел или \"-\" для составного отчества. Первая буква должна быть заглавной.")

        if len(Author.objects.filter(name=cleaned_data["name"], surname=cleaned_data["surname"], patronymic=cleaned_data["patronymic"])) != 0:
            raise forms.ValidationError("Автор с указанным ФИО уже существует.")
        return cleaned_data


class BookForm(forms.ModelForm):
    class Meta:
        model = Book
        fields = ["inventoryNumber", "bookName", "amount", "publishingHouse", "yearOfPublishing",  'authors']

        labels = {
            'inventoryNumber': 'Инвентарный номер',
            'bookName': 'Название',
            'amount': 'Количество',
            'publishingHouse': 'Издательство',
            'yearOfPublishing': 'Год издания'
        }
        help_texts = {
            'inventoryNumber': 'Введите инвентарный номер книги.',
            'bookName': 'Введите название книги.',
            'amount': 'Укажите количество.',
            'publishingHouse': 'Введите издательство.',
            'yearOfPublishing': 'Укажите год издания.'
        }

    authors = EmptyModelChoiceField(checker=lambda author_id: Author.objects.get(pk=author_id) is not None,
                                    label='Авторы', help_text='Выбранные авторы книги')

    all_authors = forms.ModelChoiceField(queryset=Author.objects.all(), empty_label=None, label='Доступные авторы',
                                       help_text='Выберите автора для добавления', widget=_selectpicker_widget)

    def clean(self):
        cleaned_data = super().clean()
        if (cleaned_data["amount"]) <= 0:
            raise forms.ValidationError("Неверное число книг, число книг должно быть >0")

        if (cleaned_data["yearOfPublishing"]) > datetime.datetime.now().year:
            raise forms.ValidationError("Неверный год, год должен быть меньше или равен текущему")

        author_ids = {author_id for author_id in cleaned_data["authors"]}
        new_authors = [Author.objects.get(pk=author_id) for author_id in author_ids]
        cleaned_data["authors"] = new_authors
        return cleaned_data



class SelectReaderForm(forms.Form):
    library_card = forms.ModelChoiceField(queryset=LibraryCard.objects.filter(status=True), empty_label=None, label='Читательский билет', widget=_selectpicker_widget)


class BooksChoiceField(forms.ModelChoiceField):
    def label_from_instance(self, obj):
        return str(obj) + ", доступно: " + str(obj.amount - BookInLibraryCard.books_on_hands(obj))


class AddBooksForm(forms.Form):
    amount = forms.IntegerField(label='Количество', help_text='Укажите количество для добавления')
    book = BooksChoiceField(queryset=Book.objects.all(), empty_label=None, label='Книга', help_text='Выберите книгу', widget=_selectpicker_widget)

    def clean(self):
        cleaned_data = super().clean()
        amount = cleaned_data["amount"]
        if amount <= 0:
            raise forms.ValidationError("Неправильное количество книг для добавления")
        return cleaned_data


class WriteOffBooksForm(forms.Form):
    amount = forms.IntegerField(label='Количество', help_text='Укажите количество книг для списания')
    book = BooksChoiceField(queryset=Book.objects.all(), empty_label=None, label='Книга', help_text='Выберите книгу',  widget=_selectpicker_widget)

    def clean(self):
        cleaned_data = super().clean()
        book = cleaned_data["book"]
        amount = cleaned_data["amount"]
        if amount <= 0:
            raise forms.ValidationError("Неправильное количество книг для списания")
        if book.amount - BookInLibraryCard.books_on_hands(book) - amount < 0:
            raise forms.ValidationError("Указанное количество для списания книг больше, чем доступно")
        return cleaned_data


class BooksToLibraryCardForm(forms.Form):
    books = EmptyModelChoiceField(checker=lambda book_id :len(Book.objects.filter(pk= book_id)) != 0, label='Книги для выдачи', help_text='Список выбранных для выдачи книг')

    all_books = BooksChoiceField(queryset=Book.objects.all(), empty_label=None, label='Доступные книги',
                                  help_text='Выберите книгу', widget=_selectpicker_widget)

    def clean(self):
        cleaned_data = super().clean()
        try:
            books = cleaned_data["books"]
        except KeyError:
            raise forms.ValidationError("Выбрана несуществующая книга")
        new_cleaned_data = []
        total_books = {}
        for book_id in books:
            book = Book.objects.get(pk=book_id)
            if book_id in total_books:
                total_books[book_id][0] += 1
            else:
                total_books[book_id] = [1, book]

templates/library/author_form.html
{% extends 'library/base.html' %}
{% load bootstrap_tags %}
{% block head %}
<div class="page-header">
    <h1><a href=".">Добавление автора</a></h1>
</div>
{% endblock %}
{% block content %}
<form class=form-vertical action="" method="post">
{% csrf_token %}
{{ form|as_bootstrap }}
<div class="form-actions">
<a href="/" class="btn">Отмена</a>
<button type="submit" class="btn btn-primary">Сохранить</button>
</div>
</form>
{% endblock %}

templates/library/base.html
{% load staticfiles %}
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>АЗИС БИБЛИОТЕКА</title>
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap-theme.min.css' %}">
    <link rel="stylesheet" href="{% static 'fontawesome/css/font-awesome.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
</head>
<body>
<div class="wrapper">
    <!-- Sidebar Holder -->
    <nav id="sidebar">

        {% if user.is_authenticated %}
            <ul class="list-unstyled components">
                <br>
                {% if can_use_ReaderCreate %}
                    <li><a href="/add_reader">Добавить читателя</a></li>
                {% endif %}
                <li>
                    {% if can_use_AuthorCreate %}
                        <a href="/add_author">Добавить автора</a>
                    {% endif %}
                </li>
                <li>
                    {% if can_use_BookCreate %}
                        <a href="/add_book">Добавить новую книгу</a>
                    {% endif %}
                </li>
                <li>
                    {% if can_use_SelectReader %}
                        <a href="/select_reader">Выбрать читателя</a>
                    {% endif %}
                </li>
                <li>
                    {% if can_use_ChangeBookAmount %}
                        <a href="/add_books">Добавить книги</a>
                    {% endif %}
                </li>
                <li>
                    {% if can_use_ChangeBookAmount %}
                        <a href="/write_off_books">Списать книги</a>
                    {% endif %}
                </li>
            </ul>
            {% if libcard_id != None %}
            <ul class="list-unstyled components">
                    <li><a href="/reader/{{ libcard_id }}/get_books">Выдать книги</a></li>
                    <li><a href="/reader/{{ libcard_id }}/return_books">Вернуть книги</a></li>
            </ul>
            {% endif %}
            {% if user_is_staff %}
            <ul class="list-unstyled CTAs">
                    <li><a href="/admin">Панель администрирования</a></li>
            </ul>
            {% endif %}
        {% else %}
        <ul class="list-unstyled components">
                <li><a href="/accounts/login/">Вход</a></li>
        </ul>
        {% endif %}
    </nav>

    <!-- Page Content Holder -->
    <div id="content">

        <nav class="navbar navbar-default">
            <div class="container-fluid">

                <div class="navbar-header">
                    <button type="button" id="sidebarCollapse" class="btn btn-info navbar-btn">
                        <i class="glyphicon glyphicon-align-left"></i>
                        <span>Меню</span>
                    </button>
                </div>

                <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                    <ul class="nav navbar-nav navbar-right">
                        {% if user.is_authenticated %}
                             <h3>{{ user_first_name }} {{ user_last_name }}</h3>
                            <a href="/accounts/logout/" class="btn btn-primary">Выход</a>
                        {% endif %}
                    </ul>
                </div>
            </div>
        </nav>

        <div class="content container">
            <div class="row">
                <div class="col-md-8">
                    {% block head %}
                        <div class="page-header">
                            <h1><a href="/">АЗИС БИБЛИОТЕКА</a></h1>
                        </div>
                    {% endblock %}
                    {% block content %}
                    {% endblock %}
                </div>
            </div>
        </div>


        <!-- jQuery CDN -->
        <script src="{% static 'external/jquery-1.12.0.min.js' %}"></script>
        <!-- Bootstrap Js CDN -->
        <script src="{% static 'external/bootstrap.min.js' %}"></script>
        <script type="text/javascript">
            $(document).ready(function () {
                $('#sidebarCollapse').on('click', function () {
                    $('#sidebar').toggleClass('active');
                });
            });
        </script>
    </div>
</div>
</body>
</html>

templates/library/book_form.html
{% extends 'library/base.html' %}
{% load staticfiles %}
{% load bootstrap_tags %}
{% block head %}
<link rel="stylesheet" href="{% static 'external/bootstrap-select.css' %}" />
<script src="{% static 'external/jquery-1.12.0.min.js' %}"></script>
<script src="{% static 'external/bootstrap-select.js' %}"></script>

<script type="text/javascript">
    function selectAll()
    {
        var selectBox = document.getElementById("id_authors");
        for (var i = 0; i < selectBox.options.length; i++) {
             selectBox.options[i].selected = true;
        }
    }

    function addToSelected() {
        var options = $('#id_all_authors option:selected').sort().clone();
        $('#id_authors').append(options);
    }

    function remove() {
        $('#id_authors option:selected').remove();
    }

    function removeAll() {
        $('#id_authors').empty();
    }

</script>
<div class="page-header">
    <h1><a href=".">Добавление книги</a></h1>
</div>
{% endblock %}
{% block content %}
<form class=form-vertical action="" method="post">
{% csrf_token %}
{{ form|as_bootstrap }}
    <input type="button" class="btn btn-primary" onclick="addToSelected()" value="Добавить в список"></input>
    <input type="button" class="btn btn-primary" onclick="remove()" value="Убрать выбранные"></input>
    <input type="button" class="btn btn-primary" onclick="removeAll()" value="Убрать все"></input>
    <br><br>
<div class="form-actions">
<a href="/" class="btn">Отмена</a>
<button type="submit" class="btn btn-primary" onclick="selectAll()">Сохранить</button>
</div>
</form>
{% endblock %}

templates/library/books_to_libcard_form.html
{% extends 'library/base.html' %}
{% load staticfiles %}
{% load bootstrap_tags %}
{% block head %}
<link rel="stylesheet" href="{% static 'external/bootstrap-select.css' %}" />
<script src="{% static 'external/jquery-1.12.0.min.js' %}"></script>
<script src="{% static 'external/bootstrap-select.js' %}"></script>

<script type="text/javascript">
    function selectAll()
    {
        var selectBox = document.getElementById("id_books");
        for (var i = 0; i < selectBox.options.length; i++) {
             selectBox.options[i].selected = true;
        }
    }

    function addToSelected() {
        var options = $('#id_all_books option:selected').sort().clone();
        $('#id_books').append(options);
    }

    function remove() {
        $('#id_books option:selected').remove();
    }

    function removeAll() {
        $('#id_books').empty();
    }

</script>
<div class="page-header">
    <h1><a href=".">Выдача книг</a></h1>
</div>
{% endblock %}
{% block content %}
<form class=form-vertical action="" method="post">
{% csrf_token %}
{{ form|as_bootstrap }}
    <input type="button" class="btn btn-primary" onclick="addToSelected()" value="Добавить в список"></input>
    <input type="button" class="btn btn-primary" onclick="remove()" value="Убрать выбранные"></input>
    <input type="button" class="btn btn-primary" onclick="removeAll()" value="Убрать все"></input>
    <br><br>
<div class="form-actions">
<a href="/reader/{{ libcard_id }}/" class="btn">Отмена</a>
<button type="submit" class="btn btn-primary" onclick="selectAll()">Сохранить</button>
</div>
</form>
{% endblock %}

templates/library/change_book_amount.html
{% extends 'library/base.html' %}
{% load staticfiles %}
{% load bootstrap_tags %}
{% block head %}
<link rel="stylesheet" href="{% static 'external/bootstrap-select.css' %}" />
<script src="{% static 'external/jquery-1.12.0.min.js' %}"></script>
<script src="{% static 'external/bootstrap-select.js' %}"></script>
<div class="page-header">
    <h1><a href=".">Изменение количества книг</a></h1>
</div>
{% endblock %}
{% block content %}
<form class=form-vertical action="" method="post">
{% csrf_token %}
{{ form|as_bootstrap }}
    <br><br>
<div class="form-actions">
<a href="/" class="btn">Отмена</a>
<button type="submit" class="btn btn-primary">Сохранить</button>
</div>
</form>
{% endblock %}

templates/library/index.html
{% extends 'library/base.html' %}
{% block content %}
{% if can_use_ReaderCreate %}
<ul class="list-unstyled components">
    <li><a href="add_reader">Добавить читателя</a></li>
</ul>
{% endif %}
{% if can_use_AuthorCreate %}
<ul class="list-unstyled components">
    <li><a href="add_author">Добавить автора</a></li>
</ul>
{% endif %}
{% if can_use_BookCreate %}
<ul class="list-unstyled components">
    <li><a href="add_book">Добавить новую книгу</a></li>
</ul>
{% endif %}
{% if can_use_SelectReader %}
<ul class="list-unstyled components">
    <li><a href="select_reader">Выбрать читателя</a></li>
</ul>
{% endif %}
{% if can_use_ChangeBookAmount %}
<ul class="list-unstyled components">
    <li><a href="add_books">Добавить книги</a></li>
</ul>
{% endif %}
{% if can_use_ChangeBookAmount %}
<ul class="list-unstyled components">
    <li><a href="write_off_books">Списать книги</a><li>
</ul>
{% endif %}
{% if not user.is_authenticated %}
<ul class="list-unstyled components">
    <li><a href="accounts/login/">Вход</a></li>
</ul>
{% endif %}
{% endblock %}

templates/library/login.html
{% extends 'library/base.html' %}
{% load bootstrap_tags %}
{% block content %}
<form class=form-vertical action="" method="post">
    <input type="hidden" name="next" value="/" />
    {% csrf_token %}
    {{ form|as_bootstrap_inline }}
    <button type="submit" class="btn btn-primary">Войти</button>    
    <a href="/" class="btn">Отмена</a>
</form>
{% endblock %}

templates/library/reader_form.html
{% extends 'library/base.html' %}
{% load bootstrap_tags %}
{% block head %}
<div class="page-header">
    <h1><a href=".">Добавление читателя</a></h1>
</div>
{% endblock %}
{% block content %}
<form class=form-vertical action="" method="post">
{% csrf_token %}
{{ form|as_bootstrap }}
<div class="form-actions">
<a href="/" class="btn">Отмена</a>
<button type="submit" class="btn btn-primary">Сохранить</button>
</div>
</form>
{% endblock %}

templates/library/reader_index.html
{% extends 'library/base.html' %}
{% block head %}
<div class="page-header">
    <h1><a href=".">Читатель</a></h1>
</div>
{% endblock %}
{% block content %}
    <h3>Информация о читателе:</h3>
    <table>
        <tr><td>ФИО:</td><td>{{ reader.surname }} {{ reader.name }} {{ reader.patronymic }}</td></tr>
        <tr><td>Паспортные данные:</td><td>{{ passportSeries }} {{passportNumber }}</td></tr>
        <tr><td>Телефон:</td><td>{{ reader.phoneNumber }}</td></tr>
        <tr><td>Номер читательского билета:</td><td>{{ libcard_id }}</td></tr>
    </table>
<br>
<br>
<a href="/reader/{{ libcard_id }}/get_books">Выдать книги</a><br>
<a href="/reader/{{ libcard_id }}/return_books">Вернуть книги</a><br>
<br>
{% endblock %}

templates/library/return_books_form.html
{% extends 'library/base.html' %}
{% load bootstrap_tags %}
{% block head %}
<div class="page-header">
    <h1><a href=".">Возврат книг</a></h1>
</div>
{% endblock %}
{% block content %}
<form class=form-vertical action="" method="post">
{% csrf_token %}
{{ form|as_bootstrap }}
<div class="form-actions">
<a href="/reader/{{ libcard_id }}/" class="btn">Отмена</a>
<button type="submit" class="btn btn-primary">Сохранить</button>
</div>
</form>
{% endblock %}

templates/library/select_reader_form.html
{% extends 'library/base.html' %}
{% load staticfiles %}
{% load bootstrap_tags %}
{% block head %}
<link rel="stylesheet" href="{% static 'external/bootstrap-select.css' %}" />
<script src="{% static 'external/jquery-1.12.0.min.js' %}"></script>
<script src="{% static 'external/bootstrap-select.js' %}"></script>
<div class="page-header">
    <h1><a href=".">Выбор читателя</a></h1>
</div>
{% endblock %}
{% block content %}
<form class=form-vertical action="" method="post">
{% csrf_token %}
{{ form|as_bootstrap }}
    <br><br>
<div class="form-actions">
<a href="/" class="btn">Отмена</a>
<button type="submit" class="btn btn-primary">Выбрать</button>
</div>
</form>
{% endblock %}